In [21]:
import tensorflow as tf

In [22]:
x=tf.constant(4.0,shape=(2,4),dtype=tf.float32)

In [23]:
print(x)

tf.Tensor(
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]], shape=(2, 4), dtype=float32)


In [29]:
x=tf.ones((2,2))

In [30]:
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [37]:
x=tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [38]:
x=tf.eye(3)
print(x)
#Identity matrix

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [40]:
a=tf.constant([1,2,3],dtype=tf.int32)
b=tf.constant([4,5,6],dtype=tf.int32)
c=tf.add(a,b)
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [41]:
print(tf.subtract(a,b))
print()

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
